### PR TITLE
(fix): Add `swift-docc-plugin` dependency

### PR DESCRIPTION
**Pull request by engali94**
Add `swift-docc-plugin` dependency to fix the auto generated d…ocs issue (#9)

### CODE REVIEW

**Comment by omaralbeik** [comment]
Thanks @engali94! I see the [overview](https://swiftpackageindex.com/omaralbeik/Stores/main/documentation/stores) now after #16

Looks like adding this dependency is [not required anymore](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/)

> UPDATE: It’s no longer necessary to add the DocC plugin to your package. If you’ve added it already, feel free to remove it. Our build system will also cope if you leave the plugin or need it for another purpose, so there’s no rush to remove it! The only change you need to make to your project is to [add the manifest file](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/#add-a-spi-manifest).

**Comment by omaralbeik** [comment]
Now that #18 is merged, lets keep and eye on the [documentation for main](https://swiftpackageindex.com/omaralbeik/Stores/main/documentation/stores), if it doesn't help, then we can merge this and give it a shot.

**Comment by engali94** [comment]
Hey @omaralbeik I compared with other packages I spotted this difference after double checking the `spi.yml` file 
seems the platform info is missing I am updating this PR

**Comment by omaralbeik** [comment]
Thanks @engali94, this is the documentation platform, we don't need doc generation in multiple platforms for this package, I don't think we need to specify it, but lets wait to see if the new changes appear [here](https://swiftpackageindex.com/omaralbeik/Stores/main/documentation/stores) in the next 24 hr first to make sure

> Documentation platform
By default, we will generate documentation using macOS. If your package requires the documentation generation to be run for a certain platform such as iOS, you can also specify a platform:

**Comment by omaralbeik** [comment]
@engali94 Looks like the documentation is fixed now!
I'll close this one, feel free to open another one where you update the .gitignore file

**Pull request closed without merging**
